spring:
  application:
    name: test1-config

  profiles:
    active: git
  #    active: native

  cloud:
    config:
      server:
        git:
          uri: "https://github.com/bishal-ghosh900/test1-client-config-files.git"
          default-label: master
          timeout: 5
          force-pull: true
          clone-on-start: true
#        native:
#          search-locations: classpath:/config


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8070
